server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name op.fish www.op.fish _;
  client_max_body_size 2m;

  location ^~ /.well-known/acme-challenge/ {
    auth_basic off;
    root /var/www/letsencrypt;
    default_type "text/plain";
  }

  location = /api/health {
    auth_basic off;
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    return 301 https://op.fish$request_uri;
  }
}

server {
  listen 443 ssl http2 default_server;
  listen [::]:443 ssl http2 default_server;
  server_name op.fish www.op.fish _;
  client_max_body_size 2m;

  ssl_certificate /etc/letsencrypt/live/op.fish/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/op.fish/privkey.pem;

  location = /api/health {
    auth_basic off;
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
